// Copyright 2022 CeresDB Project Authors. Licensed under Apache-2.0.

package coderr

import (
	"fmt"
)

// CodeErrorWrapper is a wrapper for wrapping an error as a CodeError.
// The wrapper is often used to define the error generated by our dependency libraries.
type CodeErrorWrapper interface {
	Wrap(cause error) CodeError
}

type codeErrorWrapperImpl struct {
	code Code
	msg  string
}

func (w *codeErrorWrapperImpl) Wrap(cause error) CodeError {
	return &WrappedCodeError{
		code:  w.code,
		msg:   w.msg,
		cause: cause,
	}
}

func NewCodeErrorWrapper(code Code, msg string) CodeErrorWrapper {
	return &codeErrorWrapperImpl{
		code,
		msg,
	}
}

type WrappedCodeError struct {
	code  Code
	msg   string
	cause error
}

func (e *WrappedCodeError) Error() string {
	return fmt.Sprintf("code:%d, msg:%v, cause:%v", e.code, e.msg, e.cause)
}

func (e *WrappedCodeError) Code() Code {
	return e.code
}
